title: Ashley Kaku # your name (or website title) here
logo: "/images/1688568170949.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Data-driven Professional:<br><br>
  Finding new ways to bring success through data  <br><br>
  <a href="https://www.linkedin.com/in/ashleykaku/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
